apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tlsbench-data
  namespace: tlsbench
  labels:
    app.kubernetes.io/name: tlsbench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: gp3-csi
