apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tlsbench-edge
  namespace: tlsbench
  labels:
    app.kubernetes.io/name: tlsbench
    tlsbench.termination: edge
spec:
  to:
    kind: Service
    name: tlsbench
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
